
### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "aac2@aaa.fr",
    "password": "azerty"
}

### Sign in
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "aac@aaa.fr",
    "password": "azerty"
}

### Get the currently signed in user
GET http://localhost:3000/auth/whoami

### Sign out
POST http://localhost:3000/auth/signout


### Find a particular user with a given id
GET http://localhost:3000/auth/2

### Find all users with a given email
GET http://localhost:3000/auth?email=aaa@aaa.fr

### Delete a particular user with a given id
DELETE http://localhost:3000/auth/1

### Update an user
PATCH http://localhost:3000/auth/2
content-type: application/json

{
    "email": "bbb@bbb.com"
}

### Set a color (session)
GET http://localhost:3000/auth/colors/red

### Get a color (session)
GET http://localhost:3000/auth/colors


