
### List all message
# GET http://localhost:3000/messages


### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "xavier@muselli.fr",
    "password": "azerty"
}

### Get a particular message
# GET http://localhost:3000/messages/123




